### ISSUE TITLE
Hello! Ask for help about xlladdins

### ISSUE THREAD

**Issue by weiluming** [xlladdins/xll#13]
I'm a newcomer to excel-addin, and I'm very 
interested in it! I met you on the Internet!

Briefly talk about my doubts: I want to develop 
excel-addin in the official xll (c++) way, but I 
only found an excel sdk (excel c api) on 
Microsoft's official website
（https://www.microsoft.com/en-us/download/details.aspx?id=35567）, 
which indicates in the introduction that this sdk 
(c api) supports the excel 2013 version. What I 
want to know is whether this sdk (c api)
supports the new versions like excel 2016 、
excel 2019 、microsoft 365? In other words: Is 
there any xll sdk (c api) of excel2016 、
excel2019 、microsoft365 downloaded 
separately, or whether the corresponding 
version of sdk (c api) has been automatically 
installed when installing office? If it is installed 
automatically, how to find it and use it。

Thank you very much!

**Comment by rmcrkd** [comment]
Hello there. this xll library (where you have posted your issue) *does* support microsoft 365. I am using it with microsoft 365, and microsoft 365 is recommended for the best experience (see readme). to the best of my knowledge, there is no "official xll (c++) way" beyond the excel 2013 xll sdk available [here](https://docs.microsoft.com/en-us/office/client-developer/excel/welcome-to-the-excel-software-development-kit). So, it sounds like you should just use this xll library (and why not?)
