### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by c-jamie** [xlladdins/xll#16]
This is my first time working with CPP on windows so I've likely misconfigured something.

I've cloned xll_template.

`git clone https://github.com/xlladdins/xll_template`

Then pulled the submodule.

`git submodule update --init --recursive`

When I compile the project I get a stream of errors (attached).

[build_errors.txt](https://github.com/xlladdins/xll/files/7840905/build_errors.txt)

If it helps, my project looks like this: 
![image](https://user-images.githubusercontent.com/44546398/148815010-d55e9775-e539-44a1-8ddf-fd5e4b056a95.png)

Any help would be appreciated - thanks!

**Comment by keithalewis** [comment]
Do not update the submodule.

**Comment by c-jamie** [comment]
Thanks for the quick reply.

If I clone the project `git clone https://github.com/xlladdins/xll_template` only.

I get `C:\Users\jamie\code\ak\xll_template1\xll_template.vcxproj : error  : The imported project "C:\Users\jamie\code\ak\xll_template1\xll\xll.props" was not found. Confirm that the expression in the Import declaration "xll\xll.props" is correct, and that the file exists on disk.  C:\Users\jamie\code\ak\xll_template1\xll_template.vcxproj`

I also tried `git clone https://github.com/c-jamie/xll_template1.git  --recurse-submodules`

I get the same large error output.

**Comment by keithalewis** [comment]
Did you try `git clone https://github.com/c-jamie/xll_template1.git` without updating the submodule?

**Comment by c-jamie** [comment]
Yes I got this error:
 C:\Users\jamie\code\ak\xll_template1\xll_template.vcxproj : error : The imported project "C:\Users\jamie\code\ak\xll_template1\xll\xll.props" was not found. Confirm that the expression in the Import declaration "xll\xll.props" is correct, and that the file exists on disk. C:\Users\jamie\code\ak\xll_template1\xll_template.vcxproj

**Comment by keithalewis** [comment]
Go to https://github.com/xlladdins/xll_template and click `Use this template` to create a new repository. Clone that repository. DO NOT UPDATE the xll submodule. I just built this in VS2019 using these steps.
You can always try cloning https://github.com/xlladdins/xll and building that.

**Comment by c-jamie** [comment]
I'll try this - thanks.
