### ISSUE TITLE
Get Started doesn't work

### ISSUE THREAD

**Issue by pausti2** [xlladdins/xll#19]
When using the template to generate the new repository under get started instructions, the xll_template.sln is not a valid solution. I think the problem is that the xll directory is empty and so one required project is missing. Probably I am doing something wrong?
Thank you very much

**Comment by keithalewis** [comment]
Works for me in VS 2019 and 2022. What is the url of the repository generated from the template?

**Comment by pausti2** [comment]
Thank you for the super-fast reply. It was a private repo but I just did the same and made it public:
https://github.com/pausti2/xlldemo2
I am using Microsoft Visual Studio Community 2022 (64-bit)
Apologies if I am doing something silly

**Comment by keithalewis** [comment]
I cloned the link above into VS 2022, clicked on OK to retarget, opened xll_template.sln, selected xll_template as the startup project and pressed F5. Everything built and (64-bit) Excel started in the debugger with the add-in loaded.
You may have to hit Ctrl-N in Excel to get a new window.
Let me know if this is not working for you.

**Comment by pausti2** [comment]
Thank you, I used SourceTree to pull https://github.com/pausti2/xlldemo2. It has pulled xll_template.sln and other files in the same directory, but it hasn't pulled anything into the xll directory (it's just an empty directory).

I have just tried this:
>cd xll
>git pull origin master
and it outpus this:
From https://github.com/pausti2/xlldemo
 * branch            master     -> FETCH_HEAD
Already up to date.

Clearly an issue on my side as I can see the xla folder and content in the github web interface. Can you think what the issue could be?

**Comment by pausti2** [comment]
Ah, this worked (run from the main folder)

git submodule update --init xll

Thank you again for your help

**Comment by keithalewis** [comment]
Glad you are up and running. My guess is that it is a Sourcetree issue. Submodules seem to be a work-in-progress on GitHub.
You can use update to get the latest version of the xll library. Submodules are not automatically updated.
