### ISSUE TITLE
Unicode text in function arg names, descriptions and etc

### ISSUE THREAD

**Issue by rentocika** [xlladdins/xll#2]
Hello! In previos version of XLL I use russian text for function arguments descriptions? help text and much more by using wstring with _T(). How to do this in new version? Thank you!

**Comment by keithalewis** [comment]
Молодец! The new library uses UTF-8 at the user level and converts to MBCS (Excel4) or UTF-16 (Excel12 and later) behind the scenes as appropriate. Here is the [**fix**](https://github.com/xlladdins/xll/blob/master/xll/utf8.h#L24) that now uses the correct code page.
The [`XLL.MACRO`](https://github.com/xlladdins/xll/blob/master/test/test.cpp#L19) example should display "XLL.MACRO called with активный cell: ..." now. 
Let me know if you find anything else amiss. Большой спасибо!

**Comment by rentocika** [comment]
Thank you! Fixed.
