### ISSUE TITLE
Unavailable link for "Use this  template" under Get Started

### ISSUE THREAD

**Issue by KSDXLL** [xlladdins/xll#23]
I would like to learn how to create .xll from scratch.

However, I found that the link provided under Get Started is broken:
![image](https://user-images.githubusercontent.com/122557785/212138545-3f338cb5-63e3-4eaa-b183-ba75bbf0be7d.png)

Could you please suggest?

Thanks a lot!

**Comment by keithalewis** [comment]
It points to https://github.com/xlladdins/xll_template/generate. Try again?

**Comment by KSDXLL** [comment]
noted.

Do I need to download all the files in XLL folder in the link below as well?
https://github.com/xlladdins/xll

Thanks

**Comment by keithalewis** [comment]
No

**Comment by KSDXLL** [comment]
When I download the files from link "Use this template" in the the link below, 
https://github.com/xlladdins/xll_template/generate

I got the files as screenshot below, however, the folder "xll" has no any file inside
![image](https://user-images.githubusercontent.com/122557785/212797430-250d756f-ab1b-4161-9ff9-a71bef44d786.png)

When I open the file "xll_template.sln", then I got this in Microsoft Visual Studio:

Or do I need to use "Clone a repository" in Visual Studio instead of double click the file "xll_template.sln"

Thanks a lot for your clarification

**Comment by keithalewis** [comment]
I'm not clear on what you mean by "download the files from the link". When I click on the link I see:
![image](https://user-images.githubusercontent.com/1321634/212803405-05cc2f2f-7677-4882-acda-4d03a50c1c2b.png)
I am going to post this now to see how it shows up on github. You seem to be more advanced than I am with doing this.

**Comment by keithalewis** [comment]
I think I'm getting the hang of this now:
![image](https://user-images.githubusercontent.com/1321634/212804074-712f023f-498b-4790-bf47-2745c41acb5d.png)
Click on **Create repository from template**.

I see:
![image](https://user-images.githubusercontent.com/1321634/212804428-8b30b4f4-5470-40fe-8da3-66617e8c57a2.png)

.

**Comment by keithalewis** [comment]
Tap on Code and Open with Visual Studio. You might have to click on `xll_template.sln` to open the solution.
If you are using Visual Studio 2022 then F5 will build the xll and start Excel with the add-in loaded.
It can work with older versions but there are two more steps.

**Comment by KSDXLL** [comment]
ok thanks a lot!
now, it seems to be working. 

Previously, instead of Code and Open with Visual Studio, I click on Code and Download Zip.

Thanks a again, I'm quite new to Github as well as Xll with C++, now I will start learning to create some UDF from this.

**Comment by keithalewis** [comment]
You know enough to close an issue when it has been resolved. Time for you to get to work on what you are passionate about and have people open issues on what you create. Keep me in your loop on your journey.👍
