### ISSUE TITLE
there're many work to do if you want to compile under linux using i686-w64-mingw32-g++

### ISSUE THREAD

**Issue by hitblackjack** [xlladdins/xll#24]
msvc is so ambiguous.
there're so many work to do if you want to compile under linux using i686-w64-mingw32-g++.

for example, this code can't be compiled under gcc
` 
 Args& Arguments(const std::vector<Arg>& args) 
{
       return Arguments(std::initializer_list<Arg>(&args[0], &args[0] + args.size()));  
}
`

let alone so many wchar_t to char stuff.

**Comment by keithalewis** [comment]
The library only works for Windows. That is the only platform Microsoft supports for Excel add-ins.
