### ISSUE TITLE
xml files that has the name of each method, are generated when xll starting

### ISSUE THREAD

**Issue by theangkko** [xlladdins/xll#27]
when I make test.xll that is copy of template, several wired xml files are generated in same folder that "test.xll" store.
If I want to prohibit this, how can change my setup? in project file of visual studio.

<br><br>

<img width="464" alt="image" src="https://github.com/xlladdins/xll/assets/75212211/ac1c6a53-80bb-4f96-880d-1ecfc43bec91">

**Comment by keithalewis** [comment]
Comment out https://github.com/xlladdins/xll/blob/481178bced1022f0b36b582388b79a6eabe1a11f/test/test.cpp#L18

**Comment by theangkko** [comment]
thanks! I solved
I did not guess that this is one of method (auto generation documentation function)


<img width="597" alt="image" src="https://github.com/xlladdins/xll/assets/75212211/e6275e5d-4544-4998-a17e-a3b9a78174cf">
