### ISSUE TITLE
In Release config there is many link errors

### ISSUE THREAD

**Issue by rentocika** [xlladdins/xll#3]
Hello! 

I Fillow instrucitons described in main page and I Can't compile in relese configuration? but in debug all compiled:
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK2001	неразрешенный внешний символ ___asan_load1.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Предупреждение	C6001	Использование неинициализированной памяти "*tmp".	IAPWS	D:\Projects\IAPWS\xll\xll\oper.h	549	
Предупреждение	LNK4197	несколько раз указан экспорт "_xll_spreadsheet@0"; использована первая спецификация	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_load2.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_load4.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_load8.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_memcpy.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_memmove.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(paste.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_memset.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_load1.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_load2.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_load4.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_load8.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(paste.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_store1.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_store2.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_store4.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_report_store8.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(paste.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_set_shadow_00.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(paste.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_set_shadow_f8.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(error.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_store1.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_store2.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(auto.obj)	1	
Ошибка	LNK2001	неразрешенный внешний символ ___asan_store4.	IAPWS	D:\Projects\IAPWS\IAPWS\xll.lib(spreadsheet.obj)	1	
Ошибка	LNK1120	неразрешенных внешних элементов: 20	IAPWS	D:\Projects\IAPWS\Release\IAPWS.xll	1

**Comment by keithalewis** [comment]
Привет, товарищ. You need to install [Address Sanitizer](https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/), or simply turn it off as described in the link.

**Comment by rentocika** [comment]
Solved! Thank you!

**Comment by rentocika** [comment]
So, now it's compiled with Address Sanitizer in debug and release mode, but in release mode Excel crashing and in debug mode I see in VS2019 output (sorry for russian, but I think this is no problem for You =) ):
"EXCEL.EXE" (Win32). Загружено "C:\PROGRA~2\MICROS~2\Office14\EXCEL.EXE". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ntdll.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\kernel32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\KernelBase.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\apphelp.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\AcGenral.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msvcrt.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\sechost.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\rpcrt4.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\shlwapi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\user32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\win32u.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\gdi32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\gdi32full.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msvcp_win.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ucrtbase.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ole32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\combase.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\oleaut32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\shell32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\advapi32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\uxtheme.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\winmm.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\samcli.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msacm32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\version.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\userenv.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\dwmapi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\urlmon.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\winspool.drv". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\mpr.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\sspicli.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\winmmbase.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\iertutil.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\SHCore.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\imm32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9625_none_508ef7e4bcbbe589\msvcr90.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Microsoft Office\Office14\GFX.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Microsoft Office\Office14\OART.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\wtsapi32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msimg32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ninput.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\MSO.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\bcrypt.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.488_none_11b1e5df2ffd8627\comctl32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\Cultures\OFFICE.ODF". 
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\Cultures\OFFICE.ODF"
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\Cultures\OFFICE.ODF". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msctf.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\1049\MSOINTL.DLL". 
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\1049\MSOINTL.DLL"
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\1049\MSOINTL.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\MSORES.DLL". 
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\MSORES.DLL"
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\MSORES.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\kernel.appcore.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\bcryptprimitives.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\srpapi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\crypt32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\clbcatq.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msimtf.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\RICHED20.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.685_none_4299dbb28a92ae3e\GdiPlus.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\mscoree.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OfficeSoftwareProtectionPlatform\OSPPC.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\powrprof.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\umpdc.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\TextInputFramework.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\CoreUIComponents.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\CoreMessaging.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ws2_32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ntmarta.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\WinTypes.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\WinTypes.dll". 
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\WinTypes.dll"
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\windows.storage.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\wldp.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\cfgmgr32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\propsys.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\profapi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Windows Defender\MpOAV.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Windows Defender\MpClient.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\gpapi.dll". 
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Windows Defender\MpClient.dll"
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\coml2.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\wintrust.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\msasn1.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\mssign32.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\imagehlp.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ncrypt.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\wininet.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\ntasn1.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\cryptsp.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\rsaenh.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\cryptbase.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\TextShaping.dll". 
Поток 0x4330 завершился с кодом 1 (0x1).
"EXCEL.EXE" (Win32). Загружено "D:\Projects\IAPWS\Debug\IAPWS.xll". Символы загружены.
"EXCEL.EXE" (Win32). Выгружено "D:\Projects\IAPWS\Debug\IAPWS.xll"
"EXCEL.EXE" (Win32). Загружено "D:\Projects\IAPWS\Debug\IAPWS.xll". Символы загружены.
"EXCEL.EXE" (Win32). Загружено "C:\PROGRA~2\MICROS~2\Office14\XLCALL32.DLL". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\DataExchange.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\d3d11.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\dcomp.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\dxgi.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\twinapi.appcore.dll". 
"EXCEL.EXE" (Win32). Загружено "C:\Windows\SysWOW64\winsta.dll". 
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0xC004F012.
Поток 0x5b74 завершился с кодом 0 (0x0).
"EXCEL.EXE" (Win32). Загружено "C:\Program Files (x86)\Microsoft Office\Office14\MSOSTYLE.DLL". 
Вызвано исключение по адресу 0x75BFA892 (KernelBase.dll) в EXCEL.EXE: 0x0000071A: The remote procedure call was canceled, or if a call time-out was specified, the call timed out.
"EXCEL.EXE" (Win32). Выгружено "C:\PROGRA~2\MICROS~2\Office14\XLCALL32.DLL"
"EXCEL.EXE" (Win32). Выгружено "D:\Projects\IAPWS\Debug\IAPWS.xll"
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Microsoft Office\Office14\MSOSTYLE.DLL"
Поток 0xb08 завершился с кодом 0 (0x0).
Поток 0x5718 завершился с кодом 0 (0x0).
Поток 0x6a6c завершился с кодом 0 (0x0).
Поток 0x2b50 завершился с кодом 1 (0x1).
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\mscoree.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\Cultures\OFFICE.ODF"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\msasn1.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\wintrust.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE14\RICHED20.DLL"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\imagehlp.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\ntasn1.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\ncrypt.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\wininet.dll"
"EXCEL.EXE" (Win32). Выгружено "C:\Windows\SysWOW64\mssign32.dll"
Поток 0x6718 завершился с кодом 0 (0x0).
Поток 0x740 завершился с кодом 0 (0x0).
Поток 0x2038 завершился с кодом 0 (0x0).
Поток 0x15ac завершился с кодом 0 (0x0).
Поток 0x45a0 завершился с кодом 0 (0x0).
Поток 0x1acc завершился с кодом 0 (0x0).
Поток 0x631c завершился с кодом 0 (0x0).
Поток 0x1cac завершился с кодом 0 (0x0).
Поток 0x530c завершился с кодом 0 (0x0).
Поток 0x5e88 завершился с кодом 0 (0x0).
Поток 0x52d0 завершился с кодом 0 (0x0).
Поток 0x49dc завершился с кодом 0 (0x0).
Поток 0x4cf4 завершился с кодом 0 (0x0).
Поток 0x40d4 завершился с кодом 0 (0x0).
Поток 0x49a0 завершился с кодом 0 (0x0).
Поток 0x58cc завершился с кодом 0 (0x0).
Поток 0x3114 завершился с кодом 0 (0x0).
Поток 0x59f8 завершился с кодом 0 (0x0).
Поток 0xf80 завершился с кодом 0 (0x0).
Поток 0x6540 завершился с кодом 0 (0x0).
Поток 0x65fc завершился с кодом 0 (0x0).
Поток 0x28e4 завершился с кодом 0 (0x0).
Поток 0x60dc завершился с кодом 0 (0x0).
Программа "[5544] EXCEL.EXE" завершилась с кодом 0 (0x0).

**Comment by keithalewis** [comment]
It this the output window when run in Debug with ASAN on? Is it different when ASAN is off?
Excel crashes for me in Release also when using a dll built with ASAN on. 
Maybe ASAN is not ready for primetime in VS yet.

**Comment by keithalewis** [comment]
Closing this. If you still have problems with Visual Studio's evolving support for ASAN open a new issue and let me know the version you are using.
