### ISSUE TITLE
Excel Functions - Parameters Info strings not showing

### ISSUE THREAD

**Issue by GlennGitHubAcc** [xlladdins/xll#5]
Hi:

In the EXCEL function wizard the parameter info strings are not showing (see attached screenshots) even though they are setup in the XLL.

Any suggestions on what is wrong?

This is a Windows 10 x64 build.

Thanks.
Glenn
![Excel](https://user-images.githubusercontent.com/55176232/106234722-b41d5580-6227-11eb-8d42-28f59e0b1b4e.png)
![XLL](https://user-images.githubusercontent.com/55176232/106234733-b67faf80-6227-11eb-9e1a-963378316041.png)

**Comment by keithalewis** [comment]
Just like VBA! Kidding. Fixed in e553110363e08677aca23cf57ea4b2e5408dcc9b

**Comment by GlennGitHubAcc** [comment]
Thanks Kieth - should this update be available.  When I do a GIT PULL I don't see any updates.

Also another point, when passing XLL_CSTRINGs they seem to get truncated after 23/24 characters.  Is there anyway around this?
Thanks

**Comment by keithalewis** [comment]
Please send me a https://en.wikipedia.org/wiki/Minimal_working_example.

**Comment by GlennGitHubAcc** [comment]
Sorry - checking further it was my mistake.   Apologies.

Is e553110 checked in so I can update my files?  Thanks again.

**Comment by keithalewis** [comment]
No worries. You helped me find a bug in my Args rewrite. If all is well now please close this issue.
As a by-the-by, you can also write `{XLL_TYPE, "name", "description"}` without the `Arg({...})`.

**Comment by GlennGitHubAcc** [comment]
Sorry - the parameter string problem still doesn't seem to be fixed in my build.  Is there something else I need to do?

**Comment by keithalewis** [comment]
Send me a MWE if you are still seeing problems.

**Comment by GlennGitHubAcc** [comment]
[GNGStructuralLib.zip](https://github.com/xlladdins/xll/files/5951561/GNGStructuralLib.zip)
Hi Keith:
I tried to create a MWE to illustrate the problem.  I deleted the XLL template, reinstalled it and created  a new project.  I started off with just a few routines and it all seems to work ok including displaying the parameter labels correctly.  However, when I add a few more routines, the XLL seems to fall apart and EXCEL won't load it.  These routines have all loaded correctly before.  I have attached the project - if you have any suggestions I would really appreciate it.

**Comment by keithalewis** [comment]
Hi @GlennGitHubAcc , I was able to build and run the 64-bit version in MSVC 2019 Preview. Spot checking shows the functions in the function wizard and the argument prompts look okay. Maybe you should try extracting your zip file and doing a fresh build like I just did.
If loading fails you can Debug/Break All then look at the call stack to detect where it is hanging.

**Comment by GlennGitHubAcc** [comment]
Hi:
Loaded the latest update and all seems to work now.  Thanks.

**Comment by keithalewis** [comment]
I fixed a bug in OPER memory management. I was neglecting to use placement new on malloced memory. Thanks for pointing me in the right direction.
